- bot/admin/web/angular.json
- bot/admin/web/karma.conf.js
- bot/admin/web/package.json
- bot/admin/web/src/app/faq/common/components/edit-utterance/edit-utterance.component.html
- bot/admin/web/src/app/faq/common/components/edit-utterance/edit-utterance.component.ts
- bot/admin/web/src/app/faq/common/model/form-problems.ts
- bot/admin/web/src/app/faq/faq-definition/faq-header/faq-header.component.html
- bot/admin/web/src/app/faq/faq-definition/faq-header/faq-header.component.scss
- bot/admin/web/src/app/faq/faq-definition/sidepanels/faq-sidepanel-editor-content/faq-sidepanel-editor-content.component.html
- bot/admin/web/src/app/shared/bot-shared.module.ts
- bot/admin/web/src/app/shared/error-helper/error-helper.component.css
- bot/admin/web/src/app/shared/error-helper/error-helper.component.html
- bot/admin/web/src/app/shared/error-helper/error-helper.component.spec.ts
- bot/admin/web/src/app/shared/error-helper/error-helper.component.ts
- bot/admin/web/src/test.ts
- bot/admin/web/src/tsconfig.app.json
- bot/admin/web/src/tsconfig.spec.json
- Ajout de la configuration pour mettre en place des tests unitaires
- Modification de l'en tête de filtres de FAQ Management
> DERCBOT-188 - Gestion des erreurs de saisie lors de l'ajout d'une FAQ

- bot/admin/web/src/app/bot/story/simple-answer.component.ts
- bot/admin/web/src/app/bot/story/step.component.ts
- bot/admin/web/src/app/bot/story/steps.component.ts
- nlp/admin/web/src/app/intents/intents.component.ts
Avoid js errors when cancelling dialogs by clicking on backdrop
> Fix errors on dialog closing

- bot/admin/web/src/app/faq/common/_sidepanel_layout.scss
- bot/admin/web/src/app/faq/common/components/inview-sidepanel/inview-sidepanel.component.html
- bot/admin/web/src/app/faq/common/components/inview-sidepanel/inview-sidepanel.component.scss
- bot/admin/web/src/app/faq/faq-definition/faq-definition.component.html
- bot/admin/web/src/app/faq/faq-definition/faq-definition.component.scss
- bot/admin/web/src/app/faq/faq-definition/faq-header/faq-header.component.scss
> feature: aligner le bouton FAQ sur la droite

- nlp/admin/web/src/app/applications/application-upload/application-upload.component.html
- nlp/admin/web/src/app/model/application.ts
- nlp/front/service/src/main/kotlin/ApplicationCodecService.kt
- nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
- nlp/front/service/src/main/kotlin/storage/FaqDefinitionDAO.kt
- nlp/front/service/src/test/kotlin/AbstractTest.kt
- nlp/front/service/src/test/kotlin/ApplicationCodecServiceTest.kt
- nlp/front/shared/src/main/kotlin/ApplicationConfiguration.kt
- nlp/front/shared/src/main/kotlin/codec/ApplicationDump.kt
- nlp/front/shared/src/main/kotlin/codec/ImportReport.kt
- nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
- nlp/front/storage-mongo/src/test/kotlin/FaqDefinitionMongoDAOTest.kt
Le draft est à enlever lorsque la faq_dercbot_240 sera mergé, et lorsque celle-ci rebasé
> DERCBOT-209 : Ajout des FAQ dans l'import d'un bot (full app dump)

- bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
- nlp/front/shared/src/main/kotlin/config/FaqDefinition.kt
- nlp/front/storage-mongo/src/main/kotlin/FaqDefinitionMongoDAO.kt
- nlp/front/storage-mongo/src/test/kotlin/AbstractTest.kt
- nlp/front/storage-mongo/src/test/kotlin/FaqDefinitionMongoDAOTest.kt
Corrections OK suite à modifs documentDB
> :bug: avoid documentDB troubles when searching FAQ with aggregation let pipeline

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/commons/utils.ts
- bot/admin/web/src/app/scenarios/scenario-designer/mode-stepper/mode-stepper.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-designer.service.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-production/scenario-production.component.ts
Vérifications d'intégrité du scenario
> feat(scenario-designer): scenario integrity checks

- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception.component.scss
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-production/scenario-production.component.scss
- bot/admin/web/src/app/shared/bot-shared.module.ts
- bot/admin/web/src/app/shared/directives/autofocus/autofocus.directive.spec.ts
- bot/admin/web/src/app/shared/directives/autofocus/autofocus.directive.ts
- bot/admin/web/src/app/shared/directives/index.ts
- bot/admin/web/src/app/shared/json-previewer/json-previewer.component.ts
- corrections bugs
- ajout d'une directive autofocus
> Todos front

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/context-create/context-create.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intent-create/intent-create.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intent-create/intent-create.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intent-edit/intent-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-edit/scenario-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-edit/scenario-edit.component.ts
- bot/admin/web/src/app/shared/directives/autofocus/autofocus.directive.spec.ts
- A l'ouverture des modals, mettre le focus sur le 1er champ à renseigner
- Utilisation de tockFormControl dans la modal de création d'une intention
> Scenarios todos front

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/models/scenario.model.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-designer.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.ts
- bot/admin/web/src/app/scenarios/services/scenario.service.ts
- Fix a prblm with intents post
- Inform user when the scenario id doesn't exist
> Scenarios : fix + scenario loading 

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/scenario-designer/mode-stepper/mode-stepper.component.scss
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-production/scenario-production.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-production/scenario-production.component.scss
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.html
- bot/admin/web/src/app/theme/styles/utilities.scss
- production: update html / css for small device
- publication: add card and break word class
> Scénario designer

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception.component.ts
- bot/admin/web/src/app/shared/json-previewer/json-previewer.component.html
- move action of json viewer to the footer
- disable drag&drop and keyboard shortcuts outside writing mode
> Scenario designer

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.ts
Note : Je PR ce petit commit pour pas l'oublier avant de changer de branche
> Check step validity on publishing stage before proposing to publish

- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/commons/scenario-validation.ts
- bot/admin/web/src/app/scenarios/models/scenario.model.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/intents-search/intents-search.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-designer.service.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.ts
- bot/admin/web/src/app/scenarios/scenarios-list/scenario-export/scenario-export.component.ts
- bot/admin/web/src/app/scenarios/scenarios-list/scenario-import/scenario-import.component.ts
- bot/admin/web/src/app/scenarios/scenarios-list/scenario-list-simple/scenario-list-simple.component.ts
- bot/admin/web/src/app/scenarios/scenarios.module.ts
- bot/admin/web/src/app/scenarios/services/scenario.service.ts
- nlp/admin/web/src/app/core-nlp/rest/rest.service.ts
Export scenario sentences
Clear existing sentences on reload of imported scenario
Add validation test for contexts not referenced anywhere
Add validation test for triggers not referenced anywhere
> sentences export import

- bot/admin/web/package-lock.json
- bot/admin/web/package.json
- bot/admin/web/src/app/scenarios/TODO.txt
- bot/admin/web/src/app/scenarios/models/designer.model.ts
- bot/admin/web/src/app/scenarios/models/scenario.model.ts
- bot/admin/web/src/app/scenarios/models/tickstory.model.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.scss
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.spec.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.spec.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.ts
- bot/admin/web/src/app/shared/components/form-control/form-control.component.html
- bot/admin/web/src/app/shared/components/form-control/form-control.component.ts
Gestion des unknownAnswers en multilangue au niveau des actions
Ajout de l'unknownActionsConfigs au payload du post de tickStory
> unknownAnswers front

- bot/admin/web/src/app/scenarios/models/scenario.model.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-designer.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-publishing/scenario-publishing.component.ts
allow to remove unknown answer from action + check existance of unknown answer on scenario import
> DERCBOT-416-457

- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.html
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/action-edit/action-edit.component.scss
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-conception/scenario-conception-item.component.ts
- bot/admin/web/src/app/scenarios/scenario-designer/scenario-designer.component.ts
Do not update answer with server version on reload if answer string was modified in designer
> DERCBOT-462 : Fix not required answer update on reload

- bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
- bot/engine/src/main/kotlin/connector/ConnectorData.kt
- add conversationData property to ConnectorData
- add conversationID in conversationData in Iadvize ConnectorData
> [DERCBOT-417]

- bot/engine/src/main/kotlin/engine/BotBus.kt
- save usertimeline  before switch story
> [DERCBOT-440]

- bot/admin/server/src/main/kotlin/service/ScenarioService.kt
- bot/admin/server/src/test/kotlin/service/ScenarioServiceTest.kt
- set to null the 'enabled' property of a scenarioGroup while importing
> [DERCBOT-415]

- bot/storage-mongo/src/main/kotlin/StoryDefinitionConfigurationMongoDAO.kt
- Fix aggregation to get stories that have no history (builtin stories)
> [DERCBOT-469]

- bot/admin/server/src/main/kotlin/mapper/ScenarioMapper.kt
- bot/admin/server/src/main/kotlin/model/scenario/ScenarioGroupRequest.kt
- bot/admin/server/src/main/kotlin/service/ScenarioGroupService.kt
- bot/admin/server/src/main/kotlin/service/ScenarioSettingsService.kt
- bot/admin/server/src/main/kotlin/service/StoryService.kt
- bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
- bot/admin/server/src/test/kotlin/mapper/ScenarioMapperTest.kt
- bot/admin/server/src/test/kotlin/service/ScenarioServiceTest.kt
- bot/admin/server/src/test/kotlin/service/ScenarioSettingsServiceTest.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/TickStorySettings.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/handling-step.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/unknown/TickUnknownConfiguration.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/unknown/UnknownAnswerConfig.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickStoryProcessor.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickUnknownHandler.kt
- bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioGroup.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioGroupDAO.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioSettings.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioSettingsDAO.kt
- bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfigurationDAO.kt
- bot/storage-mongo/src/main/kotlin/StoryDefinitionConfigurationMongoDAO.kt
- bot/storage-mongo/src/main/kotlin/ioc.kt
- bot/storage-mongo/src/main/kotlin/scenario/ScenarioGroupMongoDAO.kt
- bot/storage-mongo/src/main/kotlin/scenario/ScenarioSettingsMongoDAO.kt
- nlp/front/storage-mongo/src/main/kotlin/MongoIoc.kt
> [DERCBOT-470] - default scenario's unknown answer

- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickStoryProcessor.kt
- Manage answer when if the final action has no answer
> [DERCBOT-463] End the conversation if the final action has no answer

- bot/admin/server/src/main/kotlin/service/StoryService.kt
- fix Problème de publication de scénario
> [DERCBOT-458]

- bot/admin/server/src/main/kotlin/mapper/ScenarioMapper.kt
- bot/admin/server/src/main/kotlin/model/scenario/ScenarioGroupRequest.kt
- bot/admin/server/src/main/kotlin/service/ScenarioGroupService.kt
- bot/admin/server/src/main/kotlin/service/ScenarioSettingsService.kt
- bot/admin/server/src/main/kotlin/service/StoryService.kt
- bot/admin/server/src/main/kotlin/verticle/ScenarioSettingsVerticle.kt
- bot/admin/server/src/test/kotlin/mapper/ScenarioMapperTest.kt
- bot/admin/server/src/test/kotlin/service/ScenarioServiceTest.kt
- bot/admin/server/src/test/kotlin/service/ScenarioSettingsServiceTest.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/TickStory.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/TickStorySettings.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/handling-step.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/unknown/TickUnknownConfiguration.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/bean/unknown/UnknownAnswerConfig.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickStoryProcessor.kt
- bot/dialog-manager/core/src/main/kotlin/ai/tock/bot/processor/TickUnknownHandler.kt
- bot/dialog-manager/core/src/test/kotlin/ai/tock/bot/processor/TickStoryProcessorTest.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioGroup.kt
- bot/engine/src/main/kotlin/admin/scenario/ScenarioGroupDAO.kt
- bot/engine/src/main/kotlin/admin/story/StoryDefinitionConfigurationDAO.kt
- bot/storage-mongo/src/main/kotlin/StoryDefinitionConfigurationMongoDAO.kt
- bot/storage-mongo/src/main/kotlin/ioc.kt
- bot/storage-mongo/src/main/kotlin/scenario/ScenarioGroupMongoDAO.kt
- nlp/front/service/src/main/kotlin/storage/ScenarioSettingsDAO.kt
- nlp/front/shared/src/main/kotlin/config/ScenarioSettings.kt
- nlp/front/storage-mongo/src/main/kotlin/MongoIoc.kt
- nlp/front/storage-mongo/src/main/kotlin/ScenarioSettingsMongoDAO.kt
Reverts CreditMutuelArkea/tock#182
> Revert "[DERCBOT-470] - default scenario's unknown answer"

- bot/api/service/src/main/kotlin/BotApiHandler.kt
- bot/api/service/src/test/kotlin/BotApiHandlerTest.kt
- bot/engine/src/main/kotlin/engine/BotBus.kt
- bot/engine/src/main/kotlin/engine/config/ConfiguredStoryHandler.kt
- bot/storage-mongo/src/main/kotlin/UserTimelineMongoDAO.kt
> [DERCBOT-476] Make usertimeline saving synchronous

- bot/admin/server/src/main/kotlin/BotAdminService.kt
- bot/admin/server/src/main/kotlin/service/ScenarioGroupService.kt
- bot/admin/server/src/main/kotlin/service/ScenarioSettingsService.kt
- bot/admin/server/src/main/kotlin/service/ScenarioVersionService.kt
- bot/admin/server/src/main/kotlin/service/StoryService.kt
- bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
- fix test by adding getter function to all injected kodein instance
> [DERCBOT-518] - Fix tests 

- bot/admin/server/src/main/kotlin/FaqAdminService.kt
- bot/admin/server/src/test/kotlin/FaqAdminServiceTest.kt
- fix error while deleting a FAQ with shared intent
> [DERCBOT-277] -  fix error delete FAQ with shared intent

- bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
- rollback delete story endpoint
> [DERCBOT-524] - fix 405 error while trying to delete a story

- docs/_fr/admin/supervision.md
- nlp/api/client/pom.xml
- nlp/api/client/src/main/kotlin/TockNlpClient.kt
- shared/src/main/kotlin/Retrofits.kt
Add : `tock_retrofit_log_level`
And default value as NONE if production
> [DERCBOT-559] :technologist: add retrofit logging environment

- bot/api/service/src/main/kotlin/BotApiDefinition.kt
- bot/engine/src/main/kotlin/admin/bot/BotConfiguration.kt
- bot/engine/src/main/kotlin/definition/BotDefinition.kt
- bot/engine/src/main/kotlin/definition/BotDefinitionBase.kt
- bot/engine/src/main/kotlin/definition/Intent.kt
- bot/engine/src/main/kotlin/engine/config/BotDefinitionWrapper.kt
- bot/storage-mongo/target/generated-sources/kapt/compile/ai/tock/bot/admin/bot/BotConfiguration_.kt
- bot/storage-mongo/target/generated-sources/kapt/compile/ai/tock/bot/admin/bot/BotConfiguration_Deserializer.kt
- bot/storage-mongo/target/generated-sources/kapt/compile/ai/tock/bot/admin/bot/BotConfiguration_Serializer.kt
- nlp/admin/server/src/main/kotlin/AdminService.kt
- nlp/admin/server/src/main/kotlin/model/UpdateSentencesQuery.kt
- nlp/admin/web/src/app/model/nlp.ts
- nlp/admin/web/src/app/search/search.component.html
- nlp/admin/web/src/app/sentence-analysis/sentence-analysis.component.html
- nlp/admin/web/src/app/sentence-analysis/sentence-analysis.component.ts
- nlp/core/shared/src/main/kotlin/Intent.kt
- nlp/front/service/src/main/kotlin/ApplicationConfigurationService.kt
- nlp/front/service/src/main/kotlin/ParserService.kt
- nlp/front/storage-mongo/src/main/kotlin/ClassifiedSentenceMongoDAO.kt
Ne pas oublier de ne pas prendre en compte le FRONT qui va être redéveloppé
> [DERCBOT-655] new predefined intent - tock:ragexcluded

- bot/connector-iadvize/src/main/kotlin/IadvizeConnector.kt
Ready to merge
See my comment on the jira ticket, to see the rendering,
> [DERCBOT-741] IAdvize - Message with markdown

- bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
Reverts CreditMutuelArkea/tock#300
> Revert "[DERCBOT-840] Limit rag access to admin"

- bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
- bot/admin/server/src/main/kotlin/model/BotGenerateSentencesConfigurationDTO.kt
- bot/admin/server/src/main/kotlin/service/GenerateSentencesService.kt
- bot/admin/server/src/main/kotlin/service/GenerateSentencesValidationService.kt
- bot/engine/src/main/kotlin/admin/bot/generatesentences/BotGenerateSentencesConfiguration.kt
- bot/engine/src/main/kotlin/admin/bot/generatesentences/BotGenerateSentencesConfigurationDAO.kt
- bot/storage-mongo/src/main/kotlin/BotGenerateSentencesConfigurationMongoDAO.kt
- bot/storage-mongo/src/main/kotlin/ioc.kt
création du système de sauvegarde et de validation de la configuration pour la génération de phrases d'entrainement
> [DERCBOT-778] Bot Admin - sauvegarde config géneration phrases entrainement

- gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/configurations/environement/settings.py
- gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/azure_openai_llm_factory.py
- gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/factories/llm/openai_llm_factory.py
Following comments from https://github.com/CreditMutuelArkea/tock/pull/322
> [DERCBOT-898] Rename timeout variable

- bot/admin/server/src/main/kotlin/BotAdminVerticle.kt
- bot/admin/server/src/main/kotlin/model/BotSentenceGenerationConfigurationDTO.kt
- bot/admin/server/src/main/kotlin/model/BotSentenceGenerationInfoDTO.kt
- bot/admin/server/src/main/kotlin/model/OptionsGenerateSentencesRequest.kt
- bot/admin/server/src/main/kotlin/service/CompletionService.kt
- bot/engine/src/main/kotlin/admin/bot/sentencegeneration/BotSentenceGenerationConfiguration.kt
Attention : Do not merge on 901. Waiting for DERCBOT-948
> [DERCBOT-944] Update sentence generation endpoints and add nbSentence
